apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../apps/postgres/overlays/local
- ../../apps/minio/overlays/local
- ../../apps/mlflow/overlays/local
- ../../apps/api/overlays/local
- ../../apps/ui/overlays/local
